name: aruco_estimator
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - pip
  - pip:
    - open3d==0.15.1
    - opencv-contrib-python==4.6.0.66
    - opencv-python==4.6.0.66
    - pyquaternion==0.9.9
    - matplotlib
    - tqdm==4.64.0
    - wget==3.2
