[tool.poetry]
name = "aruco-estimator"
version = "1.1.11"
description = ""
authors = [
    'Lukas Meyer <lukas.meyer@fau.de>',
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "3.5.2"
numpy = "1.22.4"
opencv-contrib-python = "*"
tqdm = "4.64.0"
wget = "3.2"
pyquaternion = "0.9.9"
pyransac3d = "0.6.0"
pycolmap = "^3.11.1"
open3d = "^0.18.0"
colmap-wrapper = "^1.1.5"
scikit-learn = "1.3.2"
pyyaml = "^6.0.2"
addict = "^2.4.0"
pandas = "*"
opencv-python = "*"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"

[tool.ruff]
select = ["F403"]  
extend-select = ["I"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
