[tool.poetry]
name = "aruco-estimator"
version = "1.1.12"
description = ""
authors = [
    'Lukas Meyer <lukas.meyer@fau.de>',
    'Nile Walker <nilezwalker@gmail.com>'
    'Michael Currie <mcurrie@gmail.com>'
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
matplotlib = "3.5.2"
numpy = ">=1.22.4"
tqdm = "4.64.0"
pyquaternion = "0.9.9"
pyransac3d = "0.6.0"
pycolmap = "^3.11.1"
open3d = "^0.19.0"
colmap-wrapper = "^1.1.5"
scikit-learn = "1.3.2"
pyyaml = "^6.0.2"
addict = "^2.4.0"
pandas = "2.0.3"
opencv-python = "4.10.0.84"
opencv-contrib-python = "4.10.0.84"
click = "^8.1.8"
pyceres = "2.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.8.4"
ipykernel = "^6.29.5"

[tool.poetry.scripts]
aruco-estimator = "aruco_estimator.cli:main"

[tool.ruff]
select = ["F403"]  
extend-select = ["I"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
